version: '2.2'
services:
  postgres-server: #name of the first service
    image: medium/database:latest
    container_name: postgres-server
    restart: always
    volumes:
      - /opt/workspace/docker/data/medium:/var/lib/postgresql/data:rw
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432" #specify ports forewarding
    mem_limit: 1g
    mem_reservation: 512m
    cpus: 1.5
    networks:
      microservice_network:
        aliases:
          - postgres-server
  eureka-service:
    image: 'eureka-service:latest'
    restart: always
    volumes:
      - /opt/workspace/docker/data/logs:/logs:rw
    ports:
      # both ports must match the port from external_url above
      - "8761:8761"
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 1
    networks:
      microservice_network:
        aliases:
          - eureka-service  
  menusync-service:
    image: 'menusync-service:latest'
    restart: always
    volumes:
      - /opt/workspace/docker/data/logs:/logs:rw
    mem_limit: 256m
    mem_reservation: 128m
    cpus: 0.5
    links:
     - postgres-server
    depends_on:
      - "eureka-service"
      - "postgres-server"
    networks:
      microservice_network:
  zuul-service:
    image: 'zuul-service:latest'
    restart: always
    volumes:
      - /opt/workspace/docker/data/logs:/logs:rw
    ports:
      # both ports must match the port from external_url above
      - "8081:8081"
    mem_limit: 256m
    mem_reservation: 128m
    cpus: 0.5
    depends_on:
      - "eureka-service"
      - "menusync-service"
    networks:
      microservice_network:
networks:
  microservice_network:
    ipam:
      driver: default